# Generated by Django 5.0.4 on 2024-05-25 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(default='placeholder.jpg', upload_to='')),
                ('category', models.CharField(blank=True, choices=[('Menu', 'Menu'), ('Hamburguesas', 'Hamburguesas'), ('pizza P', 'Pizzeta'), ('pizza M', 'Pizza Mediana'), ('pizza F', 'Pizza Familiar'), ('Bocadillo', 'Bocadillo'), ('Sandwich', 'Sandwich'), ('Perrito', 'Perrito'), ('Picoteo', 'Picoteo'), ('Bebida', 'Bebida'), ('Postre', 'Postre')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
