# Generated by Django 5.0.4 on 2024-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Menu', 'Menu'), ('Hamburguesas', 'Hamburguesas'), ('Pizzeta', 'Pizzeta'), ('Pizza Mediana', 'Pizza Mediana'), ('Pizza Familiar', 'Pizza Familiar'), ('Bocadillo', 'Bocadillo'), ('Sandwich', 'Sandwich'), ('Perrito', 'Perrito'), ('Picoteo', 'Picoteo'), ('Bebida', 'Bebida'), ('Postre', 'Postre')], max_length=100),
        ),
    ]
