# Generated by Django 5.0.4 on 2024-05-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
